###############################################################################
#   Copyright (C) 2020 Simon Adlem, G7RZU <g7rzu@gb7fr.org.uk>
#   Edited by (C) 2022 Shane Daley, MOVUB <support@gb7nr.co.uk>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
###############################################################################

version: '2.4'
services:
    rysen:
        container_name: systemx
        cpu_shares: 1024
        mem_reservation: 600m
        volumes:
            - '/etc/rysen/rysen.cfg:/opt/rysen/rysen.cfg'
            - '/var/log/rysen/:/opt/rysen/log/'
            - '/etc/rysen/rules.py:/opt/rysen/rules.py'
            #Write JSON files outside of container
            - '/etc/rysen/json/:/opt/rysen/json/'
        ports:
            #Change the below to include ports used for your OBP(s)
            - '62034-62050:62034-62050/udp'
              #HBMon Port (Report)
            - '4321:4321/tcp'
              #APRS Master
            - '52555:52555/udp'          
        image: 'shaymez/rysen:latest'
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.10
             ipv6_address: fd2a:70b6:9f54:29b6::10
        read_only: "true"
    ipv6nat:
        container_name: ipv6nat
        image: 'robbertkl/ipv6nat'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - '/lib/modules:/lib/modules:ro'
        privileged: "true"
        network_mode: "host"
        restart: "unless-stopped"
networks:
  app_net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        - subnet: fd2a:70b6:9f54:29b6::/64
          gateway: fd2a:70b6:9f54:29b6::1
