version: '2.4'
services:
    rysen:
        container_name: rysen
        cpu_shares: 1024
        mem_reservation: 600m
        volumes:
            - '/etc/rysen/rysen.cfg:/opt/rysen/rysen.cfg'
            - '/var/log/rysen/rysen.log:/opt/rysen/rysen.log'
            - '/etc/rysen/rules.py:/opt/rysen/rules.py'
            #Write JSON files outside of container
            - '/etc/rysen/json/:/opt/rysen/json/'
        ports:
            - '62031:62031/udp'
            #Change the below to inlude ports used for your OBP(s)
            - '62034-62044:62034-62044/udp'
            #HBMon Port (Report)
            - '4321:4321/tcp'
        image: 'shaymez/rysen:latest'
        restart: "unless-stopped"
        #Control parameters inside container
        environment:
            #IPV6 support 
            - FDPROXY_IPV6=0
            #Display connection stats in log
            - FDPROXY_STATS=1
            #Display conneting client info in log
            - FDPROXY_CLIENTINFO=1
            #Debug HBP session in log (lots of data!!)
            - FDPROXY_DEBUG=0
            #Override proxy external port
            #- FDPROXY_LISTENPORT=62031
        read_only: "true"        
