###############################################################################
# Copyright (C) 2020 Simon Adlem, G7RZU <g7rzu@gb7fr.org.uk>  
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
###############################################################################

version: '2.4'
services:
    rysen:
        container_name: rysen
        cpu_shares: 1024
        mem_reservation: 600m
        volumes:
            - '/etc/rysen/rysen.cfg:/opt/rysen/rysen.cfg'
            - '/var/log/rysen/rysen.log:/opt/rysen/rysen.log'
            - '/etc/rysen/rules.py:/opt/rysen/rules.py'
            #Write JSON files outside of container
            - '/etc/rysen/json/talkgroup_ids.json:/opt/rysen/talkgroup_ids.json'
            - '/etc/rysen/json/subscriber_ids.json:/opt/rysen/subscriber_ids.json'
            - '/etc/rysen/json/peer_ids.json:/opt/rysen/peer_ids.json'
            - '/etc/rysen/json/sub_map.pkl:/opt/rysen/sub_map.pkl'
        ports:
            - '62031:62031/udp'
            #Change the below to inlude ports used for your OBP(s)
            - '62041:62041/udp'
        image: 'hacknix/rysen:latest'
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.10
        #Control parameters inside container
        environment:
            #IPV6 support 
            - FDPROXY_IPV6=0
            #Display connection stats in log
            - FDPROXY_STATS=1
            #Display conneting client info in log
            - FDPROXY_CLIENTINFO=1
            #Debug HBP session in log (lots of data!!)
            - FDPROXY_DEBUG=0
            #Override proxy external port
            #- FDPROXY_LISTENPORT=62031
        read_only: "true"

    rysenmon:
        container_name: rysenmon
        cpu_shares: 512
        depends_on:
            - rysen
        volumes:
            #This should be kept to a manageable size from
            #cron or logrotate outisde of the container.
            - '/var/log/RYSENmonitor/lastheard.log:/opt/RYSENmonitor/log/lastheard.log'
            - '/var/log/RYSENmonitor/hbmon.log:/opt/RYSENmonitor/log/hbmon.log'
            #Write JSON files outside of container
            - '/etc/rysen/json/talkgroup_ids.json:/opt/RYSENmonitor/talkgroup_ids.json'
            - '/etc/rysen/json/subscriber_ids.json:/opt/RYSENmonitor/subscriber_ids.json'
            - '/etc/rysen/json/peer_ids.json:/opt/RYSENmonitor/peer_ids.json'

        #Override config file
        #    - '/etc/rysen/config.py:/opt/RYSENmonitor/config.py'
        ports:
            - '9000:9000/tcp'
        image: 'hacknix/rysenmonitor:latest'
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.20
     
    rysenmonpache:
        container_name: rysenmonapache
        cpu_shares: 512
        depends_on:
             - rysenmon
        #Use to override html files
        #And images
        #volumes:
        #    - '/var/www/html/:/var/www/html/'
        #    - '/var/www/html/images/:/var/www/html/images/'
        ports:
            - '80:80/tcp'
        image: hacknix/rysenmonitor-apache:latest
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.30

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
