###############################################################################
#   Copyright (C) 2020 Simon Adlem, G7RZU <g7rzu@gb7fr.org.uk>
#   Edited by (C) 2022 Shane Daley, MOVUB <support@gb7nr.co.uk>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
###############################################################################

version: '2.4'
services:
    rysen:
        container_name: systemx
        cpu_shares: 1024
        mem_reservation: 600m
        volumes:
            - '/etc/rysen/rysen.cfg:/opt/rysen/rysen.cfg'
            - '/var/log/rysen/:/opt/rysen/log/'
            - '/etc/rysen/rules.py:/opt/rysen/rules.py'
            #Write JSON files outside of container
            - '/etc/rysen/json/:/opt/rysen/json/'
        ports:
            #Change the below to include ports used for your OBP(s)
            - '62034-62050:62034-62050/udp'
              #HBMon Port (Report)
            - '4321:4321/tcp'
              #APRS Master
            - '52555:52555/udp'          
        image: 'shaymez/rysen:latest'
        restart: "unless-stopped"
        networks:
           app_net:
             ipv4_address: 172.16.238.10
        read_only: "true"
    proxy:
        container_name: proxy
        volumes:
            - '/etc/rysen/proxy.cfg:/opt/rysen-sp/proxy.cfg'
        ports:
            - '62031:62031/udp'
        image: 'shaymez/rysen-sp:latest'
        restart: "unless-stopped"    
        depends_on:
            - 'rysen'
        networks:
            app_net:
              ipv4_address: 172.16.238.20
        read_only: "true"          
    d-aprs:
        container_name: d-aprs
        environment:
          - APRS_CALL=M0ABC-12
          - APRS_SSID=9
          - APRS_PASSCODE=12345
          - DATA_DMR_ID=9059
          - MASTER_IP=172.16.238.10
          - MASTER_PASS=daprs1234
       # volumes:
         # - '/etc/rysen/aprs/gps_data.cfg:/opt/gps_data.cfg'
         # - '/etc/rysen/aprs/usersettings.txt:/usersettings/usersettings.txt'
        image: 'shaymez/rysen-d-aprs:latest'
        #Container will persist over reboots
        restart: "unless-stopped"
        depends_on:
            - 'rysen'
            - 'proxy'
        networks:
           app_net:
             ipv4_address: 172.16.238.40
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1 